sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
linkReplacements:
  - "https://github.com/FasterXML/jackson-modules-java8/jackson-datatype-jsr310|https://github.com/FasterXML/jackson-modules-java8/"
  - "http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.txt|http://cecill.info/licences/Licence_CeCILL-C_V1-en.txt"
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_upload_github_release_assets.yml'"
  - "[WARNING] W-PK-CORE-155: Could not detect latest available version of project-keeper. Server returned HTTP response code: 504 for URL: https://search.maven.org/solrsearch/select?q=g:com.exasol+AND+a:project-keeper-maven-plugin&wt=json. Please check network connection and response from 'https://search.maven.org/solrsearch/select?q=g:com.exasol+AND+a:project-keeper-maven-plugin&wt=json'"
