language: java
jdk:
  - openjdk11
addons:
  sonarcloud:
    organization: exasol
    token:
      secure: LxcT4+3JXxhyA8uwMVyYqTJSsVFO4e+euKZDVRilaR5lX2jXlXi7fXa1PZQzK7PhmNdgvZiFVx/4273s+cr74xuS+gVOxNwqOF28yeWDfhXVmI8aVvWY2/5QXwYUadlQqbcEzYEOYrdYfwDXHgdNsNgUMgNgrv0EjDkPMAbXfazH1BUqL2Rldhg0Cg/0/u3hlQ1wGphNCMHgRMx7UoxrM54Sr8eNNuCVZwwo9o25BMn9Pa+ej7h8FgQrDijUP6C9HbOYdbzqi7QZRYBHc+a9z2Jal7uNRXUC9ujgI4PxZ26FP2rd/CTWZ/kGbaX2wS0sBwzDrl9lZpCjIObl52VjPM0kbhWOflgO3RtJ7Pi5vfvfWq9cGGjrzJwfp3MtR1RzjqUj1VgQNXWsuZ95EJNk2zZomxzp7YUyifrHvGr2FdzhCNG5F8rP0+rSErJ8qKRr3y/B11X7Pt/9zo1xB3rm4S2/MAgG0t0y2/EabufaCR0Ga5QmIr0D7r2V6p512vrmOyhBK1zAERXbtLw4//O6u49RAmqB9gc8hkQ++CGqqEaEbdm960H+N1iUjgL4OhljE2gpoIJwveOnO7EQfeuQ6PDE8sHwdNNQY/QaOGf6HLNR9A10BxVnSXo6IsTGDdM+NfrDA0aF75nEDPI41d+MszfH0scjrnuq+lXp00n+074=
install:
  - travis_retry mvn dependency:resolve
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=${SONAR_TOKEN} && mvn error-code-crawler:verify
cache:
  directories:
    - "$HOME/.m2"
